/* Actually run the fleet's assertions on a machine with no MSVC.
 *
 * `cargo test` does not exist here — `.claude/rules/build.md` has the whole of
 * why. So `bash tools/check-gnu.sh --tests` *typechecks* `flyway/fleet.rs`'s
 * assertions and cannot execute one of them.
 *
 *     bun tools/lift-fleet.ts
 *
 * ### Why this one is worth a lift
 *
 * `fleet.rs` is the protocol two machines speak, and the shape of a protocol
 * bug is one that compiles: a request relayed under the wrong tag, an answer
 * gossiped that should not be, a gate whose arms are in the wrong order. Each
 * of those was a test before it was code, and a test that only compiles is a
 * comment. The file is pure by construction — no clock, no store, no socket —
 * so, like `repair/text.rs`, it is lifted **whole**, and a test added to it is
 * run rather than quietly skipped.
 *
 * What it borrows: `serde` and `serde_json` out of the gnu target directory
 * (`check-gnu.sh` builds them), the `serde_derive` proc-macro out of the host
 * one, and `crate::clean::scrub` — the one thing in the crate the file reaches
 * — lifted verbatim out of `clean.rs` rather than restated, so a change to what
 * counts as impossible is a change to what this runs.
 */

import { readFileSync, writeFileSync, mkdtempSync, rmSync, readdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { depsDir, newestRlib, rustEnv } from "./lift-scan.ts";

const FLEET = "src-tauri/src/flyway/fleet.rs";
const CLEAN = "src-tauri/src/clean.rs";
const DEPS = depsDir();
const HOST = "src-tauri/target/debug/deps";

function rlibOf(name: string): string {
  return newestRlib(name);
}

const read = (p: string) => readFileSync(p, "utf8").replace(/\r\n/g, "\n");

/* `scrub` and the predicate it calls, and nothing else of `clean.rs` — its own
   tests are its own business. Found by name and asserted, so a rename is loud. */
const clean = read(CLEAN);
function item(src: string, head: string): string {
  const at = src.indexOf(head);
  if (at === -1) throw new Error(`${CLEAN} no longer has \`${head}\` — has it been rewritten?`);
  /* To the first line that is a lone closing brace: these are top-level fns. */
  const end = src.indexOf("\n}\n", at);
  return src.slice(at, end + 3);
}
const scrub = ["use std::borrow::Cow;", item(clean, "pub fn impossible("), item(clean, "pub fn scrub(")].join("\n");

const lift = [
  read(FLEET),
  "",
  "// GENERATED by tools/lift-fleet.ts — do not edit, do not keep.",
  "mod clean {",
  scrub,
  "}",
].join("\n");

const dir = mkdtempSync(join(tmpdir(), "lift-fleet-"));
const file = join(dir, "lifted.rs");
const exe = join(dir, "lifted.exe");
writeFileSync(file, lift);

try {
  const build = spawnSync(
    "rustc",
    [
      "--test",
      "--edition",
      "2021",
      "--crate-name",
      "fleet",
      "-A",
      "dead_code",
      "--extern",
      `serde=${rlibOf("serde")}`,
      "--extern",
      `serde_json=${rlibOf("serde_json")}`,
      "-L",
      `dependency=${DEPS}`,
      "-L",
      `dependency=${HOST}`,
      file,
      "-o",
      exe,
    ],
    /* Load-bearing, as in every lift: bare `rustc` takes the msvc default and
       dies on `link: extra operand`, which names nothing (sink b282b54c). */
    { encoding: "utf8", env: rustEnv() },
  );
  if (build.status !== 0) {
    console.error(build.stderr || build.stdout);
    console.error(`\nthe lift is at ${file} — it was NOT removed, so you can read it.`);
    process.exit(1);
  }
  const run = spawnSync(exe, ["--test-threads", "1"], { encoding: "utf8" });
  console.log(run.stdout);
  if (run.stderr) console.error(run.stderr);
  rmSync(dir, { recursive: true, force: true });
  process.exit(run.status ?? 1);
} catch (e) {
  console.error(e);
  process.exit(1);
}
